version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ToDoApp
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"

      
  frontend:
    build:
      context: ../todo-app
      dockerfile: ../todo-app/Dockerfile
    ports:
      - "8080:80"