CREATE DATABASE IF NOT EXISTS ToDoApp;

USE ToDoApp;

CREATE TABLE IF NOT EXISTS Usuarios (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Tareas (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UsuarioID INT,
    Descripcion TEXT NOT NULL,
    Fecha DATETIME NOT NULL,
    FOREIGN KEY (UsuarioID) REFERENCES Usuarios(ID)
);


